[workspace]
resolver = "2"
members = ["src/autonomous_node", "src/lights_node", "src/wheels_node"]

[patch.crates-io]
ros2-client = { git = "https://github.com/Sooner-Rover-Team/ros2-client", rev = "8ca2f85" }
