[project]
name = "autonomous"
version = "0.2.0"
requires-python = ">=3.13"

[tool.uv.sources]
# if one python project depends on another, put it here!
#
# for now, though, it's empty. :D

[tool.uv.workspace]
members = ["src/navigator_node", "src/log_node"]

[dependency-groups]
dev = [
    "colcon-cargo>=0.1.3",
    "colcon-common-extensions>=0.3.0",
    "colcon-ros-cargo>=0.2.0",
    "ruff>=0.9.4",
]
