slam_toolbox:
  ros__parameters:
    # tell the program to actually perform mapping
    mode: mapping

    # toggle for better debugging
    debug_logging: false

    # tell `slam_tb` to avoid publishing the map
    # publish_tf: false
    # transform_publish_period: -1.0 # IMPORTANT!

    # publish the map
    publish_tf: true
    transform_publish_period: 0.02
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    scan_buffer_size: 50 # we need this to avoid running outta buf space
    throttle_scans: 5 # only read every `n`th scan.
    minimum_time_interval: 0.3 # wait n seconds before processing again
    use_map_saver: false

    # define tf2 frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # ask it to use a specific solver
    solver_plugin: solver_plugins::CeresSolver

    # configure the solver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG

    # other conf.
    map_update_interval: 1.0
    transform_tolerance: 0.1
    max_laser_range: 30.0
    z_hit: 0.95
    z_rand: 0.05
    sigma_hit: 0.2

    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.001
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
