/v4l2_depth_image_left:
  ros__parameters:
    # we can differentiate video devices via their permenant USB identifier,
    # which are located in this folder: `/dev/v4l/by-id`.
    #
    # however, if someone were to change the port a camera was connected to,
    # things would end poorly.
    #
    # for more information, see:
    # https://docs.kernel.org/userspace-api/media/v4l/open.html#v4l2-device-node-naming
    video_device: "/dev/TODO_LEFT" # TODO: assign permanent usb port + get path

    # resolution in format: [width, height]
    image_size: [1280, 720] # TODO: settle on (and document) camera resolution

    # TODO: fine-tune the v4l2 camera parameters.
    #
    # see: https://docs.ros.org/en/humble/p/v4l2_camera/#parameters

    # whether to run + use a compression algorithm node
    use_image_transport: false

    # refresh the camera <n> times per second
    publish_rate: 15

    # publish sensor info with "best effort" reliability.
    #
    # this makes depth sensor data faster and allows us to keep up when under
    # high computational load
    use_sensor_data_qos: true

/v4l2_depth_image_right:
  ros__parameters:
    video_device: "/dev/TODO_RIGHT"
    image_size: [1280, 720]
    use_image_transport: false
    publish_rate: 15
    use_sensor_data_qos: true
