[project]
name = "manual_control"
description = "Utilities for controlling the Rover."
version = "1.0.0"

readme = "README.md"
dependencies = ["pygame>=2.6.1"]
dynamic = ["scripts"]

[build-system]
requires = ["setuptools>=79", "wheel"]
build-backend = "setuptools.build_meta"
