# this file controls the IMU only.
#
# it'd also work for any wheel odometry sensors (to see how much we've "really"
# moved), but we don't have those as of writing!

/**:
  ros__parameters:
    # behavior
    two_d_mode: true
    publish_tf: true

    # frame parameters
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # debug logging
    print_diagnostics: true
    debug: false
    debug_out_file: rl_ekf_filter_node_odom.log

    # configure imu for local usage
    imu0: /sensors/imu
    imu0_config: [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        # don't use acceleration on `z` axis.
        #
        # make sure to toggle this on with `two_d_mode: false`..!
        false,
      ]
    imu0_differential: false
    imu0_queue_size: 50
    # `false` if the imu reports "raw" acceleration.
    #
    # that means `az` will include gravity
    imu0_remove_gravitational_acceleration: true

    odom0: /diff_drive_controller/odom
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_config:
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ]
